In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.5)

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [4]:
url = 'https://statiz.sporki.com/stats/?m=main&m2=fielding&m3=default&so=WAAwithPOS&ob=DESC&year=2021&sy=&ey=&te=&po=&lt=10100&reg=A&pe=&ds=&de=&we=&hr=&ha=&ct=&st=&vp=&bo=&pt=&pp=&ii=&vc=&um=&oo=&rr=&sc=&bc=&ba=&li=&as=&ae=&pl=&gc=&lr=&pr=50&ph=&hs=&us=&na=&ls=&sf1=&sk1=&sv1=&sf2=&sk2=&sv2='
response = requests.get(url)

In [5]:
html = response.text
soup = BeautifulSoup(html, 'html.parser')
temp = soup.find_all("table")[0]

In [ ]:
df = pd.DataFrame(index = range(50), columns = ["Rank", "Name", "Team", "WAAwithPOS", "G", "GS", "IP", "TC", "PO", "Ass", "E", "F%", "RF9", "Range RAA",
                                                 "Arm RAA", "Err RAA", "DP RAA", "Bt RAA", "CS RAA", "Blk RAA", "Frm RAA", "종합 RAA", "/144", "POSAdj", "RAAwithPOS", "WAAwoPOS", "WAAwithPOS"])

df

In [7]:
l = 0
trs = temp.find_all("tr")
for j in range(2, min(414, len(trs))):  # 리스트의 길이를 벗어나지 않도록 조정
    temp2 = trs[j]
    if len(temp2.find_all("td")) == 27:
        for i in range(27):
            tds = temp2.find_all("td")
            if i < len(tds):  # 리스트의 길이를 벗어나지 않도록 조정
                temp3 = tds[i]
                df.iloc[l,i] = temp3.get_text()
            else:
                # 만약 인덱스가 범위를 벗어난 경우 처리할 내용 추가
                pass
        l += 1

df

,Rank,Name,Team,WAAwithPOS,G,GS,IP,TC,PO,Ass,...,Bt RAA,CS RAA,Blk RAA,Frm RAA,종합 RAA,/144,POSAdj,RAAwithPOS,WAAwoPOS,WAAwithPOS
0,1,오지환,21 SS,2.706,132,129,1060.2,547,175,359,...,,,,,17.83,19.16,10.46,28.29,1.705,2.706
1,2,마차도,21 SS,1.977,133,127,1076.2,583,235,337,...,,,,,9.99,10.74,10.68,20.67,0.956,1.977
2,3,최재훈,21 C,1.655,108,100,842.0,765,702,62,...,0.32,1.83,3.51,-1.00,6.94,8.61,10.37,17.30,0.663,1.655
3,4,강승호,21 2B,1.639,103,82,686.1,368,137,226,...,,,,,14.06,17.92,3.08,17.14,1.345,1.639
4,5,심우준,21 SS,1.557,138,129,1065.0,556,210,327,...,,,,,7.12,7.38,9.16,16.28,0.681,1.557
5,6,김태군,21 C,1.502,100,76,666.0,622,568,48,...,0.25,0.88,3.81,4.78,9.16,12.93,6.55,15.71,0.876,1.502
6,7,장성우,21 C,1.470,110,97,813.1,748,698,43,...,-0.37,-0.84,-0.74,8.21,5.70,6.46,9.67,15.37,0.545,1.470
7,8,박성한,21 SS,1.315,129,111,993.2,530,194,313,...,,,,,4.55,4.85,9.20,13.75,0.435,1.315
8,9,김민성,21 3B,1.198,117,107,854.0,237,54,176,...,0.14,,,,12.53,14.91,0.00,12.53,1.198,1.198
9,10,장운호,21 RF,1.154,59,34,349.0,88,85,3,...,,,,,13.63,19.05,-1.56,12.07,1.303,1.154
10,11,강민호,21 C,1.144,119,110,934.0,856,800,49,...,0.14,-1.20,2.40,0.12,1.04,1.22,10.92,11.96,0.099,1.144
11,12,한승택,21 C,1.108,82,68,589.0,547,489,53,...,0.12,0.57,2.75,2.01,5.87,10.31,5.71,11.58,0.562,1.108
12,13,박찬호,21 SS,1.085,128,126,1100.1,549,204,321,...,,,,,1.71,1.88,9.64,11.35,0.163,1.085
13,14,서건창,21 2B,1.084,62,58,1038.1,568,253,307,...,,,,,5.69,5.69,5.65,11.34,0.544,1.084
14,15,박민우,21 2B,1.070,49,48,384.0,215,103,109,...,,,,,9.05,26.07,2.14,11.19,0.866,1.070
15,16,안중열,21 C,1.017,56,41,364.2,324,292,31,...,-0.04,1.92,1.46,2.96,6.91,17.16,3.72,10.63,0.661,1.017
16,17,변상권,21 LF,1.007,58,41,360.2,98,96,2,...,,,,,12.09,24.19,-1.56,10.53,1.157,1.007
17,18,김혜성,21 SS,1.006,114,104,905.2,510,159,322,...,,,,,0.86,0.86,9.66,10.52,0.082,1.006
18,19,최지훈,21 CF,0.989,105,99,670.1,223,216,6,...,,,,,10.34,10.95,0.00,10.34,0.989,0.989
19,20,송성문,21 2B,0.915,35,28,251.2,165,75,88,...,,,,,8.31,18.13,1.26,9.57,0.795,0.915
20,21,노시환,21 3B,0.877,96,94,811.0,294,98,176,...,0.31,,,,9.17,12.34,0.00,9.17,0.877,0.877
21,22,이지영,21 C,0.872,94,50,508.2,422,389,30,...,-0.01,0.27,0.58,2.57,3.67,4.89,5.45,9.12,0.351,0.872
22,23,지시완,21 C,0.864,72,52,448.1,436,395,40,...,-0.04,0.02,-2.41,5.78,4.61,9.10,4.42,9.03,0.441,0.864
23,24,김인태,21 RF,0.815,83,75,536.0,149,145,4,...,,,,,11.40,12.35,-2.88,8.52,1.091,0.815
24,25,김민식,21 C,0.789,86,67,606.0,517,470,42,...,-0.02,-0.08,-2.64,4.53,1.65,2.38,6.60,8.25,0.158,0.789
25,26,박해민,21 CF,0.784,125,119,989.2,283,280,2,...,,,,,8.20,9.30,0.00,8.20,0.784,0.784
26,27,김준태,21 C,0.771,45,31,302.0,290,267,21,...,-0.27,-1.34,0.89,5.67,4.87,12.09,3.19,8.06,0.466,0.771
27,28,이재원,21 C,0.721,104,80,678.2,596,551,38,...,-0.04,0.83,1.09,-0.47,0.38,0.52,7.15,7.54,0.037,0.721
28,29,박계범,21 SS,0.720,64,43,374.1,158,70,87,...,,,,,3.93,4.79,3.60,7.53,0.376,0.720
29,30,오윤석,21 2B,0.710,8,5,258.0,147,44,102,...,,,,,6.39,9.49,1.03,7.42,0.611,0.710
30,31,유강남,21 C,0.678,129,117,961.0,897,829,65,...,-0.42,0.59,-2.26,-2.47,-3.26,-3.61,10.34,7.09,-0.311,0.678
31,32,박세혁,21 C,0.627,96,73,575.1,549,495,50,...,-0.24,-0.11,1.67,-1.54,0.34,0.50,6.22,6.55,0.032,0.627
32,33,김용의,21 1B,0.613,79,3,155.2,169,153,15,...,0.07,,,,7.12,10.06,-0.72,6.40,0.681,0.613
33,34,김재호,21 SS,0.598,83,63,543.0,262,108,150,...,,,,,1.41,2.29,4.84,6.25,0.135,0.598
34,35,김규성,21 SS,0.595,13,6,61.0,33,11,22,...,,,,,5.84,15.57,0.38,6.22,0.558,0.595
35,36,노진혁,21 SS,0.580,65,61,503.2,225,84,136,...,,,,,1.20,1.62,4.86,6.06,0.115,0.580
36,37,예진원,21 LF,0.549,24,15,126.0,39,38,1,...,,,,,6.27,17.36,-0.53,5.74,0.600,0.549
37,38,이창진,21 CF,0.525,82,67,558.1,169,168,1,...,,,,,5.49,7.53,0.00,5.49,0.525,0.525
38,39,조수행,21 CF,0.507,36,9,140.0,63,61,1,...,,,,,5.31,6.64,0.00,5.31,0.507,0.507
39,40,최정원,21 2B,0.498,65,56,451.1,232,92,133,...,,,,,2.92,5.84,2.29,5.21,0.279,0.498
40,41,박승규,21 LF,0.489,18,9,93.1,32,32,0,...,,,,,5.55,13.54,-0.44,5.11,0.531,0.489
41,42,정진호,21 LF,0.484,41,38,302.2,82,77,3,...,,,,,6.50,19.49,-1.44,5.06,0.621,0.484
42,43,알테어,21 CF,0.471,134,129,1078.2,325,319,4,...,,,,,4.92,4.95,0.00,4.92,0.471,0.471
43,44,김웅빈,21 3B,0.465,56,42,364.2,113,32,77,...,-0.08,,,,4.86,7.22,0.00,4.86,0.465,0.465
44,45,배정대,21 CF,0.463,144,139,1189.1,318,308,7,...,,,,,4.84,4.84,0.00,4.84,0.463,0.463
45,46,김성현,21 2B,0.452,73,33,357.0,208,86,119,...,,,,,3.23,4.23,1.49,4.72,0.309,0.452
46,47,하주석,21 SS,0.427,113,111,923.2,376,131,231,...,,,,,-5.00,-5.21,9.46,4.46,-0.478,0.427
47,48,박동원,21 C,0.418,84,73,560.1,458,407,46,...,0.15,0.84,1.59,-5.09,-2.13,-2.35,6.50,4.37,-0.204,0.418
48,49,김주원,21 SS,0.403,51,40,346.1,180,73,97,...,,,,,1.30,2.70,2.92,4.22,0.124,0.403
49,50,이우성,21 LF,0.396,60,19,247.2,60,58,1,...,,,,,5.06,11.20,-0.92,4.14,0.484,0.396