In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.5)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = 'https://statiz.sporki.com/stats/?m=main&m2=pitching&m3=default&so=WAR&ob=DESC&year=2022&sy=&ey=&te=&po=&lt=10100&reg=A&pe=&ds=&de=&we=&hr=&ha=&ct=&st=&vp=&bo=&pt=&pp=&ii=&vc=&um=&oo=&rr=&sc=&bc=&ba=&li=&as=&ae=&pl=&gc=&lr=&pr=50&ph=&hs=&us=&na=&ls=&sf1=&sk1=&sv1=&sf2=&sk2=&sv2='
response = requests.get(url)

In [4]:
html = response.text
soup = BeautifulSoup(html, 'html.parser')
temp = soup.find_all("table")[0]

In [ ]:
df = pd.DataFrame(index = range(50), columns = ["Rank", "Name", "Team", "WAR", "G", "GS", "GR", "GF", "W", "L", "S", "HD", "IP", "ER",
                                                 "R", "rRA", "TBF", "H", "2B", "3B", "HR", "BB", "HP", "IB", "SO", "ROE",
                                                 "BK", "WP", "ERA", "RA9", "rRA9", "rRA9pf", "FIP", "WHIP", "WAR"])

df

In [6]:
l = 0
trs = temp.find_all("tr")
for j in range(2, min(414, len(trs))):  # 리스트의 길이를 벗어나지 않도록 조정
    temp2 = trs[j]
    if len(temp2.find_all("td")) == 35:
        for i in range(35):
            tds = temp2.find_all("td")
            if i < len(tds):  # 리스트의 길이를 벗어나지 않도록 조정
                temp3 = tds[i]
                df.iloc[l,i] = temp3.get_text()
            else:
                # 만약 인덱스가 범위를 벗어난 경우 처리할 내용 추가
                pass
        l += 1

df

,Rank,Name,Team,WAR,G,GS,GR,GF,W,L,...,ROE,BK,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR
0,1,안우진,22 P,8.45,30,30,0,1,15,8,...,6,1,7,2.11,2.34,2.33,2.36,2.09,0.95,8.45
1,2,수아레즈,22 P,6.65,30,29,1,0,6,8,...,16,0,6,2.49,3.16,3.10,3.09,2.94,1.16,6.65
2,3,김광현,22 P,6.44,28,28,0,0,13,3,...,9,0,1,2.13,2.49,2.49,2.44,3.14,1.07,6.44
3,4,요키시,22 P,6.25,30,30,0,0,10,8,...,13,0,2,2.57,2.96,2.90,3.06,2.86,1.09,6.25
4,5,뷰캐넌,22 P,5.75,26,26,0,1,11,8,...,6,0,2,3.04,3.43,3.39,3.22,3.61,1.34,5.75
5,6,반즈,22 P,5.70,31,31,0,0,12,12,...,10,0,7,3.62,4.20,3.87,3.75,3.21,1.20,5.70
6,7,루친스키,22 P,5.68,31,31,0,0,10,12,...,10,0,9,2.97,3.58,3.49,3.49,2.80,1.13,5.68
7,8,폰트,22 P,5.58,28,28,0,1,13,6,...,7,0,5,2.69,3.08,3.08,3.01,3.31,0.95,5.58
8,9,고영표,22 P,5.31,28,28,0,1,13,8,...,7,0,1,3.26,3.41,3.33,3.21,2.75,1.17,5.31
9,10,켈리,22 P,5.26,27,27,0,0,16,4,...,5,0,3,2.54,2.71,2.71,2.93,2.89,1.08,5.26
10,11,플럿코,22 P,5.26,28,28,0,0,15,5,...,10,0,5,2.39,2.94,2.81,2.95,3.19,1.01,5.26
11,12,구창모,22 P,4.85,19,19,0,0,11,5,...,5,0,7,2.10,2.58,2.43,2.43,3.03,1.08,4.85
12,13,소형준,22 P,4.70,27,27,0,0,13,6,...,11,0,6,3.05,3.57,3.50,3.39,3.41,1.15,4.70
13,14,원태인,22 P,4.67,27,27,0,0,10,8,...,8,0,3,3.92,4.08,3.99,3.86,3.72,1.29,4.67
14,15,놀린,22 P,4.31,21,21,0,0,8,8,...,9,1,4,2.47,2.98,2.90,2.96,3.05,1.12,4.31
15,16,엄상백,22 P,4.13,33,22,11,0,11,2,...,4,0,1,2.95,3.33,3.28,3.12,3.60,1.22,4.13
16,17,박세웅,22 P,3.97,28,28,0,0,10,11,...,12,0,8,3.89,4.58,4.43,4.31,2.84,1.34,3.97
17,18,곽빈,22 P,3.53,27,27,0,0,8,9,...,7,1,9,3.78,4.21,3.95,4.13,3.99,1.37,3.53
18,19,이인복,22 P,3.48,26,23,3,0,9,9,...,6,0,4,4.19,4.48,4.28,4.06,3.78,1.44,3.48
19,20,최원준,22 P,3.43,30,30,0,0,8,13,...,10,1,1,3.60,4.36,4.18,4.35,4.41,1.33,3.43
20,21,벤자민,22 P,3.10,17,17,0,0,5,4,...,6,1,3,2.70,3.17,3.17,3.02,4.04,1.02,3.10
21,22,김민우,22 P,3.09,29,29,0,1,6,11,...,9,0,13,4.36,4.53,4.31,4.33,4.61,1.39,3.09
22,23,모리만도,22 P,3.07,12,12,0,0,7,1,...,5,0,2,1.67,2.27,2.27,2.23,2.99,1.06,3.07
23,24,양현종,22 P,3.07,30,30,0,0,12,7,...,11,0,3,3.85,4.41,4.37,4.44,3.66,1.25,3.07
24,25,장민재,22 P,3.03,32,25,7,1,7,8,...,6,0,3,3.55,3.84,3.84,3.82,4.74,1.29,3.03
25,26,김재웅,22 P,2.74,65,0,65,18,3,2,...,1,0,4,2.01,2.01,2.21,2.30,3.84,1.09,2.74
26,27,나균안,22 P,2.73,39,13,26,1,3,8,...,2,0,6,3.98,4.21,4.33,4.16,2.73,1.38,2.73
27,28,김윤식,22 P,2.70,23,23,0,0,8,5,...,8,0,4,3.31,3.62,3.43,3.64,3.29,1.33,2.70
28,29,스탁,22 P,2.68,29,29,0,0,9,10,...,9,0,12,3.60,4.75,4.58,4.74,4.09,1.48,2.68
29,30,고우석,22 P,2.65,61,0,61,57,4,2,...,4,0,5,1.48,1.78,2.05,2.14,2.69,0.96,2.65
30,31,파노니,22 P,2.63,14,14,0,0,3,4,...,7,0,5,2.72,3.59,3.20,3.28,3.27,1.23,2.63
31,32,김민수,22 P,2.53,76,0,76,13,5,4,...,4,0,6,1.90,2.12,2.83,2.72,2.10,1.00,2.53
32,33,임기영,22 P,2.51,26,23,3,1,4,13,...,0,0,2,4.24,4.38,4.21,4.26,4.81,1.34,2.51
33,34,스트레일리,22 P,2.44,11,11,0,0,4,2,...,4,0,2,2.31,3.47,3.24,3.18,3.93,1.22,2.44
34,35,애플러,22 P,2.34,33,25,8,2,6,8,...,8,0,4,4.30,4.43,4.38,4.46,4.37,1.51,2.34
35,36,이의리,22 P,2.32,29,28,1,0,10,10,...,10,0,7,3.86,4.62,4.61,4.68,4.23,1.31,2.32
36,37,데스파이네,22 P,2.27,30,29,1,0,8,12,...,13,1,7,4.53,5.19,4.87,4.70,3.98,1.51,2.27
37,38,이용찬,22 P,2.24,59,0,59,49,3,3,...,4,0,1,2.08,2.37,2.73,2.73,2.68,1.14,2.24
38,39,이태양,22 P,2.15,30,17,13,3,8,3,...,7,0,0,3.62,4.02,3.96,3.78,4.76,1.25,2.15
39,40,노경은,22 P,2.15,41,8,33,7,12,5,...,5,0,5,3.05,3.16,3.28,3.13,3.86,1.15,2.15
40,41,최원태,22 P,2.08,26,20,6,0,7,5,...,7,0,5,3.75,4.26,3.98,4.15,4.18,1.26,2.08
41,42,김시훈,22 P,1.98,59,7,52,8,4,5,...,3,1,2,3.24,3.78,3.63,3.53,4.16,1.42,1.98
42,43,구승민,22 P,1.89,73,0,73,9,2,4,...,0,0,7,2.90,2.90,3.48,3.43,2.91,1.31,1.89
43,44,신민혁,22 P,1.89,26,23,3,0,4,9,...,4,1,5,4.56,4.87,4.70,4.63,4.12,1.34,1.89
44,45,오원석,22 P,1.78,31,24,7,0,6,8,...,9,0,7,4.50,4.94,4.55,4.46,4.48,1.50,1.78
45,46,백정현,22 P,1.75,24,24,0,0,4,13,...,9,0,9,5.27,5.49,5.32,5.20,5.62,1.53,1.75
46,47,김재윤,22 P,1.73,61,0,61,55,9,7,...,1,1,2,3.26,3.53,3.39,3.30,2.54,1.01,1.73
47,48,정철원,22 P,1.68,58,0,58,9,4,3,...,2,0,7,3.10,3.22,3.70,3.75,3.93,1.18,1.68
48,49,브랜든,22 P,1.62,11,11,0,0,5,3,...,7,1,2,3.60,4.02,3.90,4.03,4.35,1.23,1.62
49,50,배제성,22 P,1.54,24,18,6,4,3,9,...,3,0,8,4.21,4.71,4.57,4.26,3.96,1.39,1.54