In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.5)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = 'https://statiz.sporki.com/stats/?m=main&m2=pitching&m3=default&so=WAR&ob=DESC&year=2021&sy=&ey=&te=&po=&lt=10100&reg=A&pe=&ds=&de=&we=&hr=&ha=&ct=&st=&vp=&bo=&pt=&pp=&ii=&vc=&um=&oo=&rr=&sc=&bc=&ba=&li=&as=&ae=&pl=&gc=&lr=&pr=50&ph=&hs=&us=&na=&ls=&sf1=&sk1=&sv1=&sf2=&sk2=&sv2='
response = requests.get(url)

In [4]:
html = response.text
soup = BeautifulSoup(html, 'html.parser')
temp = soup.find_all("table")[0]

In [ ]:
df = pd.DataFrame(index = range(50), columns = ["Rank", "Name", "Team", "WAR", "G", "GS", "GR", "GF", "W", "L", "S", "HD", "IP", "ER",
                                                 "R", "rRA", "TBF", "H", "2B", "3B", "HR", "BB", "HP", "IB", "SO", "ROE",
                                                 "BK", "WP", "ERA", "RA9", "rRA9", "rRA9pf", "FIP", "WHIP", "WAR"])

df

In [6]:
l = 0
trs = temp.find_all("tr")
for j in range(2, min(414, len(trs))):  # 리스트의 길이를 벗어나지 않도록 조정
    temp2 = trs[j]
    if len(temp2.find_all("td")) == 35:
        for i in range(35):
            tds = temp2.find_all("td")
            if i < len(tds):  # 리스트의 길이를 벗어나지 않도록 조정
                temp3 = tds[i]
                df.iloc[l,i] = temp3.get_text()
            else:
                # 만약 인덱스가 범위를 벗어난 경우 처리할 내용 추가
                pass
        l += 1

df

,Rank,Name,Team,WAR,G,GS,GR,GF,W,L,...,ROE,BK,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR
0,1,미란다,21 P,7.49,28,28,0,1,14,5,...,3,1,7,2.33,2.54,2.50,2.73,2.42,1.14,7.49
1,2,백정현,21 P,6.15,27,27,0,0,14,5,...,6,0,5,2.63,3.08,3.04,2.98,4.23,1.24,6.15
2,3,원태인,21 P,6.03,26,26,0,0,14,7,...,4,1,5,3.06,3.35,3.28,3.11,3.65,1.25,6.03
3,4,루친스키,21 P,5.79,30,30,0,0,15,10,...,17,2,6,3.17,3.83,3.73,3.64,3.22,1.20,5.79
4,5,뷰캐넌,21 P,5.69,30,30,0,1,16,5,...,11,0,7,3.10,3.61,3.55,3.55,3.39,1.31,5.69
5,6,고영표,21 P,5.65,26,25,1,1,11,6,...,5,0,1,2.92,3.19,3.17,3.15,3.22,1.04,5.65
6,7,켈리,21 P,5.63,30,30,0,0,13,8,...,7,1,7,3.15,3.25,3.21,3.38,3.76,1.24,5.63
7,8,요키시,21 P,5.58,31,31,0,0,16,9,...,18,0,9,2.93,3.52,3.45,3.48,3.59,1.20,5.58
8,9,데스파이네,21 P,5.24,33,33,0,0,13,10,...,11,0,15,3.39,3.86,3.81,3.68,3.61,1.34,5.24
9,10,박세웅,21 P,5.23,28,28,0,1,10,9,...,7,0,17,3.98,4.14,4.00,3.80,4.51,1.19,5.23
10,11,최원준,21 P,4.88,29,29,0,0,12,4,...,5,0,0,3.30,3.69,3.54,3.75,4.01,1.24,4.88
11,12,수아레즈,21 P,4.52,23,22,1,0,10,2,...,6,0,2,2.18,2.58,2.58,2.75,2.66,1.14,4.52
12,13,로켓,21 P,4.49,21,21,0,1,9,9,...,3,1,1,2.98,3.19,3.11,3.35,3.34,1.40,4.49
13,14,파슨스,21 P,4.39,24,24,0,1,4,8,...,7,1,10,3.72,3.79,3.71,3.56,3.51,1.29,4.39
14,15,스트레일리,21 P,4.37,31,31,0,0,10,12,...,8,1,8,4.07,4.62,4.43,4.24,3.54,1.38,4.37
15,16,킹험,21 P,4.20,25,25,0,0,10,8,...,10,2,4,3.19,3.63,3.59,3.62,3.39,1.10,4.20
16,17,폰트,21 P,4.09,25,25,0,0,8,5,...,11,1,2,3.46,4.08,4.08,3.96,3.12,1.09,4.09
17,18,김민우,21 P,3.90,29,28,1,0,14,10,...,5,1,5,4.00,4.11,3.84,3.93,4.56,1.33,3.90
18,19,배제성,21 P,3.55,26,26,0,0,9,10,...,12,0,9,3.68,4.26,4.07,4.02,3.69,1.47,3.55
19,20,신민혁,21 P,3.51,30,25,5,2,9,6,...,4,2,2,4.41,4.66,4.52,4.46,4.36,1.37,3.51
20,21,멩덴,21 P,3.48,21,21,0,0,8,3,...,7,3,2,3.60,3.97,3.90,3.95,3.90,1.20,3.48
21,22,임기영,21 P,3.27,28,28,0,0,8,8,...,7,2,6,4.88,5.00,4.64,4.54,3.96,1.31,3.27
22,23,이의리,21 P,2.80,19,19,0,0,4,5,...,6,0,5,3.61,3.99,3.90,3.79,3.96,1.32,2.80
23,24,카펜터,21 P,2.79,31,30,1,0,5,12,...,16,1,7,3.97,4.76,4.65,4.78,3.91,1.31,2.79
24,25,안우진,21 P,2.73,21,21,0,0,8,8,...,7,1,5,3.26,3.93,3.86,3.98,4.00,1.20,2.73
25,26,정해영,21 P,2.56,64,0,64,58,5,4,...,2,0,1,2.20,2.48,3.14,3.10,4.27,1.18,2.56
26,27,오승환,21 P,2.54,64,0,64,61,0,2,...,2,0,2,2.03,2.47,3.04,2.90,2.79,1.16,2.54
27,28,쿠에바스,21 P,2.52,23,23,0,1,9,5,...,10,0,6,4.12,4.59,4.56,4.55,3.44,1.37,2.52
28,29,고우석,21 P,2.52,63,0,63,61,1,5,...,1,0,1,2.17,2.33,2.62,2.75,2.63,1.21,2.52
29,30,최채흥,21 P,2.51,26,20,6,2,5,9,...,4,1,4,4.56,4.86,4.72,4.63,4.61,1.47,2.51
30,31,정우영,21 P,2.49,70,0,70,6,7,3,...,3,0,2,2.22,2.22,2.71,2.83,3.76,1.06,2.49
31,32,곽빈,21 P,2.45,21,21,0,0,4,7,...,2,1,6,4.10,4.56,4.21,4.32,5.04,1.59,2.45
32,33,장현식,21 P,2.43,69,0,69,5,1,5,...,3,0,8,3.29,3.29,3.45,3.48,4.06,1.42,2.43
33,34,홍건희,21 P,2.39,65,0,65,11,6,6,...,0,1,7,2.78,2.78,3.28,3.36,2.62,1.24,2.39
34,35,브룩스,21 P,2.31,13,13,0,0,3,5,...,4,0,0,3.35,3.92,3.70,3.77,3.29,1.40,2.31
35,36,김택형,21 P,2.27,59,0,59,24,5,1,...,7,0,3,2.39,2.75,3.39,3.32,3.95,1.37,2.27
36,37,김재윤,21 P,2.25,65,0,65,60,4,3,...,1,0,2,2.42,2.55,3.22,3.08,3.24,1.21,2.25
37,38,이민호,21 P,2.13,25,22,3,0,8,9,...,3,0,6,4.30,4.54,4.28,4.52,4.53,1.17,2.13
38,39,정찬헌,21 P,2.13,23,23,0,1,9,5,...,6,0,3,4.01,4.33,4.30,4.59,4.00,1.40,2.13
39,40,최준용,21 P,2.12,44,0,44,6,4,2,...,1,0,1,2.85,3.04,2.81,2.69,3.95,1.20,2.12
40,41,프랑코,21 P,2.10,37,27,10,1,9,8,...,6,1,6,5.40,5.82,5.76,5.37,5.25,1.48,2.10
41,42,소형준,21 P,2.10,24,24,0,0,7,7,...,11,0,5,4.16,5.07,4.78,4.69,4.01,1.46,2.10
42,43,박종훈,21 P,2.09,9,9,0,0,4,2,...,6,2,0,2.82,3.15,3.09,3.02,3.69,1.05,2.09
43,44,김대유,21 P,1.93,64,0,64,3,4,1,...,2,0,2,2.13,2.31,2.68,2.83,2.94,0.93,1.93
44,45,한현희,21 P,1.93,18,15,3,0,6,2,...,3,0,3,3.89,4.41,3.98,4.13,3.85,1.35,1.93
45,46,김원중,21 P,1.86,61,0,61,55,4,4,...,2,0,8,3.59,3.73,4.01,3.78,3.79,1.24,1.86
46,47,김강률,21 P,1.81,50,0,50,43,3,0,...,3,0,4,2.09,2.61,3.12,3.32,3.68,1.53,1.81
47,48,강재민,21 P,1.79,58,0,58,18,2,1,...,4,1,1,2.13,2.27,3.21,3.37,3.39,1.22,1.79
48,49,임찬규,21 P,1.79,17,17,0,0,1,8,...,4,0,5,3.87,4.47,4.17,4.50,4.31,1.29,1.79
49,50,문승원,21 P,1.74,9,9,0,0,2,2,...,4,0,1,2.86,3.58,3.58,3.48,3.65,1.19,1.74