In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.5)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [22]:
url = 'https://statiz.sporki.com/stats/?m=main&m2=pitching&m3=default&so=WAR&ob=DESC&year=2023&sy=&ey=&te=&po=&lt=10100&reg=A&pe=&ds=&de=&we=&hr=&ha=&ct=&st=&vp=&bo=&pt=&pp=&ii=&vc=&um=&oo=&rr=&sc=&bc=&ba=&li=&as=&ae=&pl=&gc=&lr=&pr=50&ph=&hs=&us=&na=&ls=&sf1=&sk1=&sv1=&sf2=&sk2=&sv2='

response = requests.get(url)

In [23]:
html = response.text
soup = BeautifulSoup(html, 'html.parser')
temp = soup.find_all("table")[0]

In [ ]:
df = pd.DataFrame(index = range(50), columns = ["Rank", "Name", "Team", "WAR", "G", "GS", "GR", "GF", "W", "L", "S", "HD", "IP", "ER",
                                                 "R", "rRA", "TBF", "H", "2B", "3B", "HR", "BB", "HP", "IB", "SO", "ROE",
                                                 "BK", "WP", "ERA", "RA9", "rRA9", "rRA9pf", "FIP", "WHIP", "WAR"])

df

In [25]:
l = 0
trs = temp.find_all("tr")
for j in range(2, min(414, len(trs))):  # 리스트의 길이를 벗어나지 않도록 조정
    temp2 = trs[j]
    if len(temp2.find_all("td")) == 35:
        for i in range(35):
            tds = temp2.find_all("td")
            if i < len(tds):  # 리스트의 길이를 벗어나지 않도록 조정
                temp3 = tds[i]
                df.iloc[l,i] = temp3.get_text()
            else:
                # 만약 인덱스가 범위를 벗어난 경우 처리할 내용 추가
                pass
        l += 1

df

,Rank,Name,Team,WAR,G,GS,GR,GF,W,L,...,ROE,BK,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR
0,1,페디,23 P,7.95,30,30,0,0,20,6,...,13,0,5,2.00,2.30,2.24,2.25,2.22,0.95,7.95
1,2,후라도,23 P,7.12,30,30,0,0,11,8,...,15,0,5,2.65,3.14,3.08,3.13,3.15,1.12,7.12
2,3,안우진,23 P,6.86,24,24,0,0,9,7,...,5,0,8,2.39,2.63,2.46,2.50,2.33,1.06,6.86
3,4,뷰캐넌,23 P,6.31,30,30,0,1,12,8,...,13,1,7,2.54,3.40,3.35,3.25,3.05,1.15,6.31
4,5,고영표,23 P,5.91,28,27,1,1,12,7,...,6,0,6,2.78,2.94,2.96,2.91,3.19,1.15,5.91
5,6,알칸타라,23 P,5.79,31,31,0,0,13,9,...,11,0,3,2.67,3.14,3.14,3.34,3.38,1.07,5.79
6,7,반즈,23 P,5.74,30,30,0,0,11,10,...,7,0,7,3.28,3.59,3.46,3.41,3.40,1.33,5.74
7,8,박세웅,23 P,4.63,27,27,0,0,9,7,...,9,0,10,3.45,4.09,3.93,3.82,3.62,1.32,4.63
8,9,플럿코,23 P,4.58,21,21,0,0,11,3,...,6,0,2,2.41,2.70,2.70,2.74,3.14,1.18,4.58
9,10,쿠에바스,23 P,4.57,18,18,0,0,12,0,...,2,0,5,2.60,2.60,2.49,2.39,2.78,1.04,4.57
10,11,김광현,23 P,4.48,30,30,0,0,9,8,...,9,0,5,3.53,4.01,3.89,3.89,4.19,1.38,4.48
11,12,원태인,23 P,4.48,26,26,0,0,7,7,...,4,2,6,3.24,3.66,3.60,3.58,4.17,1.27,4.48
12,13,곽빈,23 P,4.36,23,23,0,0,12,7,...,3,1,4,2.90,3.11,2.88,3.10,3.96,1.21,4.36
13,14,페냐,23 P,4.20,32,32,0,0,11,11,...,13,4,16,3.60,4.16,4.02,3.98,4.06,1.17,4.20
14,15,브랜든,23 P,3.61,18,18,0,0,11,3,...,3,0,3,2.49,2.92,2.88,3.03,3.16,1.05,3.61
15,16,엘리아스,23 P,3.54,22,21,1,1,8,6,...,5,0,0,3.70,3.97,3.89,3.78,4.09,1.32,3.54
16,17,양현종,23 P,3.54,29,29,0,0,9,11,...,9,0,5,3.58,4.11,4.02,4.13,3.70,1.34,3.54
17,18,켈리,23 P,3.41,30,30,0,0,10,7,...,7,0,6,3.83,4.38,4.13,4.27,3.49,1.24,3.41
18,19,임찬규,23 P,3.40,30,26,4,1,14,3,...,10,1,1,3.42,3.92,3.72,3.91,4.16,1.35,3.40
19,20,나균안,23 P,3.40,23,23,0,0,6,8,...,4,0,6,3.80,4.21,4.06,3.96,3.51,1.40,3.40
20,21,맥카티,23 P,3.38,24,24,0,0,9,5,...,6,1,4,3.39,4.02,3.93,3.85,3.63,1.30,3.38
21,22,최원태,23 P,3.20,26,26,0,0,9,7,...,6,0,6,4.30,4.48,4.46,4.44,3.89,1.33,3.20
22,23,백정현,23 P,3.09,18,18,0,0,7,5,...,1,1,5,3.67,3.93,3.76,3.63,3.91,1.29,3.09
23,24,윌커슨,23 P,3.03,13,13,0,0,7,2,...,5,1,3,2.26,3.16,3.11,3.04,2.61,1.09,3.03
24,25,문동주,23 P,2.96,23,23,0,0,8,8,...,2,1,5,3.72,3.94,3.79,3.82,3.65,1.31,2.96
25,26,엄상백,23 P,2.91,20,19,1,0,7,6,...,2,0,1,3.63,3.71,3.64,3.50,3.36,1.16,2.91
26,27,벤자민,23 P,2.90,29,29,0,0,15,6,...,13,0,11,3.54,4.44,4.33,4.23,3.14,1.21,2.90
27,28,서진용,23 P,2.84,69,0,69,61,5,4,...,1,0,5,2.59,2.71,2.80,2.80,4.27,1.53,2.84
28,29,이의리,23 P,2.78,28,28,0,0,11,7,...,12,0,10,3.96,4.37,3.93,4.05,3.63,1.49,2.78
29,30,수아레즈,23 P,2.52,19,19,0,0,4,7,...,10,0,6,3.92,4.50,4.25,4.09,3.12,1.49,2.52
30,31,산체스,23 P,2.51,24,24,0,0,7,8,...,7,0,3,3.79,4.43,4.34,4.29,3.92,1.30,2.51
31,32,류진욱,23 P,2.36,70,0,70,9,1,4,...,5,0,5,2.15,2.55,2.55,2.50,3.24,1.09,2.36
32,33,함덕주,23 P,2.35,57,0,57,9,4,0,...,3,0,0,1.62,1.94,2.10,2.21,2.69,0.97,2.35
33,34,윤영철,23 P,2.27,25,24,1,0,8,7,...,5,1,4,4.04,4.33,4.11,4.21,4.55,1.40,2.27
34,35,주현상,23 P,2.21,55,0,55,9,2,2,...,1,0,0,1.96,1.96,2.26,2.29,3.25,0.84,2.21
35,36,김재윤,23 P,2.05,59,0,59,47,5,5,...,4,0,3,2.60,2.88,2.99,2.77,2.40,1.02,2.05
36,37,김진성,23 P,2.03,80,0,80,14,5,1,...,1,0,0,2.18,2.18,2.94,3.11,3.90,0.95,2.03
37,38,백승현,23 P,2.02,42,0,42,5,2,0,...,3,0,1,1.58,1.58,1.65,1.68,3.89,1.15,2.02
38,39,박영현,23 P,1.98,68,0,68,11,3,3,...,2,2,1,2.75,2.99,3.31,3.15,2.65,1.14,1.98
39,40,배제성,23 P,1.95,26,24,2,0,8,10,...,6,1,9,4.49,4.97,4.66,4.46,4.76,1.70,1.95
40,41,태너,23 P,1.94,11,11,0,0,5,2,...,3,0,0,2.92,3.62,3.43,3.45,3.81,1.10,1.94
41,42,최승용,23 P,1.94,34,20,14,4,3,6,...,7,0,3,3.97,4.38,4.22,4.44,4.03,1.35,1.94
42,43,신민혁,23 P,1.91,29,24,5,2,5,5,...,11,0,3,3.98,4.65,4.65,4.60,4.01,1.20,1.91
43,44,김동주,23 P,1.81,18,17,1,1,3,6,...,4,1,4,4.14,4.25,3.82,3.94,4.27,1.38,1.81
44,45,스트레일리,23 P,1.78,16,16,0,0,3,5,...,4,0,4,4.37,4.82,4.68,4.45,4.37,1.48,1.78
45,46,파노니,23 P,1.73,16,15,1,0,6,3,...,4,0,0,4.26,4.48,4.03,4.06,3.65,1.32,1.73
46,47,와이드너,23 P,1.71,21,20,1,0,7,5,...,7,0,3,4.54,5.09,4.94,4.80,3.66,1.32,1.71
47,48,구창모,23 P,1.70,11,9,2,0,1,3,...,5,0,0,2.96,3.31,3.10,3.06,3.02,1.05,1.70
48,49,오원석,23 P,1.64,28,27,1,1,8,10,...,10,0,11,5.23,5.72,5.49,5.31,4.90,1.57,1.64
49,50,노경은,23 P,1.64,76,0,76,6,9,5,...,4,0,8,3.58,3.58,3.95,3.92,3.81,1.37,1.64