In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

url = 'https://statiz.sporki.com/stats/?m=team&m2=batting&m3=default&so=WAR&ob=DESC&year=2022&sy=&ey=&te=&po=&lt=10100&reg=&pe=&ds=&de=&we=&hr=&ha=&ct=&st=&vp=&bo=&pt=&pp=&ii=&vc=&um=&oo=&rr=&sc=&bc=&ba=&li=&as=&ae=&pl=&gc=&lr=&pr=50&ph=&hs=&us=&na=&ls=&sf1=&sk1=&sv1=&sf2=&sk2=&sv2='

response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

team_table = soup.find_all('table')[1]  # 팀 테이블

team_df_batting_22 = pd.read_html(str(team_table))[0]  # 팀 데이터프레임

print("페이지의 팀 기록 데이터프레임:\n")

team_df_batting_22

페이지의 팀 기록 데이터프레임:

  Rank Team Unnamed: 2_level_0    정렬▼     G    PA   ePA    AB    R     H  ...  \
  Rank Team Unnamed: 2_level_1    WAR     G    PA   ePA    AB    R     H  ...
0    1   LG                 22  37.88  1735  5627  5566  4927  715  1325  ...
1    2  KIA                 22  33.82  1748  5703  5624  5000  720  1361  ...
2    3  SSG                 22  33.05  1859  5642  5550  4893  720  1245  ...
3    4   KT                 22  25.21  1890  5547  5464  4864  631  1237  ...
4    5   키움                 22  24.70  1744  5655  5589  4953  621  1250  ...
5    6   NC                 22  21.88  1770  5585  5517  4899  646  1260  ...
6    7   두산                 22  18.56  1902  5510  5447  4891  638  1249  ...
7    8   삼성                 22  18.45  1820  5647  5543  5023  663  1358  ...
8    9   한화                 22  18.11  1614  5513  5460  4878  564  1196  ...
9   10   롯데                 22  14.56  1759  5534  5446  4948  605  1320  ...

   GDP  SH  SF     비율                                      WAR▼
   GDP  SH  SF    AVG    OBP    SLG    OPS  R/ePA   wRC+   WAR▼
0  109  49  46  0.269  0.346  0.396  0.742  0.129  113.8  37.88
1  111  61  36  0.272  0.349  0.398  0.747  0.128  112.1  33.82
2   96  77  47  0.254  0.336  0.396  0.732  0.130  103.6  33.05
3  105  70  44  0.254  0.330  0.375  0.705  0.116   94.7  25.21
4   89  49  34  0.252  0.333  0.364  0.697  0.111   97.9  24.70
5  112  50  47  0.257  0.334  0.375  0.709  0.117   97.7  21.88
6  116  53  45  0.255  0.324  0.365  0.689  0.117   95.3  18.56
7  119  83  41  0.270  0.334  0.387  0.721  0.120   98.1  18.45
8   92  45  40  0.245  0.319  0.352  0.671  0.103   88.1  18.11
9  127  73  42  0.267  0.328  0.383  0.711  0.111   98.0  14.56

[10 rows x 31 columns]

In [ ]:
# 첫 번째 행을 헤더로 지정하고 데이터프레임을 새로 생성
team_2022_batting = team_df_batting_22.copy()
team_2022_batting.columns = team_2022_batting.columns.get_level_values(1)

# 첫 번째 행 제거
new_df = team_2022_batting.drop([0])

team_2022_batting

,Rank,Team,Unnamed: 2_level_1,WAR,G,PA,ePA,AB,R,H,...,GDP,SH,SF,AVG,OBP,SLG,OPS,R/ePA,wRC+,WAR▼
0,1,LG,22,37.88,1735,5627,5566,4927,715,1325,...,109,49,46,0.269,0.346,0.396,0.742,0.129,113.8,37.88
1,2,KIA,22,33.82,1748,5703,5624,5000,720,1361,...,111,61,36,0.272,0.349,0.398,0.747,0.128,112.1,33.82
2,3,SSG,22,33.05,1859,5642,5550,4893,720,1245,...,96,77,47,0.254,0.336,0.396,0.732,0.130,103.6,33.05
3,4,KT,22,25.21,1890,5547,5464,4864,631,1237,...,105,70,44,0.254,0.330,0.375,0.705,0.116,94.7,25.21
4,5,키움,22,24.70,1744,5655,5589,4953,621,1250,...,89,49,34,0.252,0.333,0.364,0.697,0.111,97.9,24.70
5,6,NC,22,21.88,1770,5585,5517,4899,646,1260,...,112,50,47,0.257,0.334,0.375,0.709,0.117,97.7,21.88
6,7,두산,22,18.56,1902,5510,5447,4891,638,1249,...,116,53,45,0.255,0.324,0.365,0.689,0.117,95.3,18.56
7,8,삼성,22,18.45,1820,5647,5543,5023,663,1358,...,119,83,41,0.270,0.334,0.387,0.721,0.120,98.1,18.45
8,9,한화,22,18.11,1614,5513,5460,4878,564,1196,...,92,45,40,0.245,0.319,0.352,0.671,0.103,88.1,18.11
9,10,롯데,22,14.56,1759,5534,5446,4948,605,1320,...,127,73,42,0.267,0.328,0.383,0.711,0.111,98.0,14.56