In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

url = 'https://statiz.sporki.com/stats/?m=team&m2=batting&m3=default&so=WAR&ob=DESC&year=2023&sy=&ey=&te=&po=&lt=10100&reg=&pe=&ds=&de=&we=&hr=&ha=&ct=&st=&vp=&bo=&pt=&pp=&ii=&vc=&um=&oo=&rr=&sc=&bc=&ba=&li=&as=&ae=&pl=&gc=&lr=&pr=50&ph=&hs=&us=&na=&ls=&sf1=&sk1=&sv1=&sf2=&sk2=&sv2='

response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

team_table = soup.find_all('table')[1]  # 팀 테이블

team_df_batting_23 = pd.read_html(str(team_table))[0]  # 팀 데이터프레임

print("페이지의 팀 기록 데이터프레임:\n")

team_df_batting_23

페이지의 팀 기록 데이터프레임:

  Rank Team Unnamed: 2_level_0    정렬▼     G    PA   ePA    AB    R     H  ...  \
  Rank Team Unnamed: 2_level_1    WAR     G    PA   ePA    AB    R     H  ...
0    1   LG                 23  37.34  1735  5687  5587  4881  767  1364  ...
1    2  KIA                 23  31.23  1840  5607  5538  4954  726  1365  ...
2    3   KT                 23  28.52  1977  5649  5585  4973  672  1316  ...
3    4   NC                 23  27.06  1807  5606  5537  4895  679  1321  ...
4    5   두산                 23  25.43  1817  5538  5462  4859  620  1238  ...
5    6  SSG                 23  23.33  1843  5630  5539  4923  658  1279  ...
6    7   한화                 23  18.97  1808  5628  5556  4906  604  1184  ...
7    8   삼성                 23  18.15  1825  5581  5499  4912  636  1290  ...
8    9   롯데                 23  17.78  1836  5576  5492  4871  653  1289  ...
9   10   키움                 23  15.85  1748  5729  5667  5062  607  1323  ...

   GDP  SH  SF     비율                                      WAR▼
   GDP  SH  SF    AVG    OBP    SLG    OPS  R/ePA   wRC+   WAR▼
0   89  94  55  0.279  0.361  0.394  0.755  0.137  119.6  37.34
1  115  63  44  0.276  0.345  0.390  0.735  0.131  107.0  31.23
2   96  57  47  0.265  0.338  0.371  0.709  0.120   98.1  28.52
3  122  63  55  0.270  0.345  0.387  0.732  0.123  104.2  27.06
4   90  57  41  0.255  0.332  0.373  0.705  0.114   99.7  25.43
5   89  77  45  0.260  0.336  0.389  0.725  0.119   99.3  23.33
6  103  59  40  0.241  0.324  0.350  0.674  0.109   90.1  18.97
7  114  77  43  0.263  0.334  0.368  0.702  0.116   93.2  18.15
8  110  75  57  0.265  0.338  0.362  0.700  0.119   96.0  17.78
9   87  51  58  0.261  0.331  0.353  0.684  0.107   92.8  15.85

[10 rows x 31 columns]

In [ ]:
# 첫 번째 행을 헤더로 지정하고 데이터프레임을 새로 생성
team_2023_batting = team_df_batting_23.copy()
team_2023_batting.columns = team_2023_batting.columns.get_level_values(1)

# 첫 번째 행 제거
new_df = team_2023_batting.drop([0])

team_2023_batting

,Rank,Team,Unnamed: 2_level_1,WAR,G,PA,ePA,AB,R,H,...,GDP,SH,SF,AVG,OBP,SLG,OPS,R/ePA,wRC+,WAR▼
0,1,LG,23,37.34,1735,5687,5587,4881,767,1364,...,89,94,55,0.279,0.361,0.394,0.755,0.137,119.6,37.34
1,2,KIA,23,31.23,1840,5607,5538,4954,726,1365,...,115,63,44,0.276,0.345,0.390,0.735,0.131,107.0,31.23
2,3,KT,23,28.52,1977,5649,5585,4973,672,1316,...,96,57,47,0.265,0.338,0.371,0.709,0.120,98.1,28.52
3,4,NC,23,27.06,1807,5606,5537,4895,679,1321,...,122,63,55,0.270,0.345,0.387,0.732,0.123,104.2,27.06
4,5,두산,23,25.43,1817,5538,5462,4859,620,1238,...,90,57,41,0.255,0.332,0.373,0.705,0.114,99.7,25.43
5,6,SSG,23,23.33,1843,5630,5539,4923,658,1279,...,89,77,45,0.260,0.336,0.389,0.725,0.119,99.3,23.33
6,7,한화,23,18.97,1808,5628,5556,4906,604,1184,...,103,59,40,0.241,0.324,0.350,0.674,0.109,90.1,18.97
7,8,삼성,23,18.15,1825,5581,5499,4912,636,1290,...,114,77,43,0.263,0.334,0.368,0.702,0.116,93.2,18.15
8,9,롯데,23,17.78,1836,5576,5492,4871,653,1289,...,110,75,57,0.265,0.338,0.362,0.700,0.119,96.0,17.78
9,10,키움,23,15.85,1748,5729,5667,5062,607,1323,...,87,51,58,0.261,0.331,0.353,0.684,0.107,92.8,15.85